added email to pool workers
src-d/ewbf-miner-docker pull request #1
Opened 2017-10-25 16:30 UTC by rporres

2017-10-25 16:59 UTC, smeruelo requested changes

2017-10-25 16:59 UTC, smeruelo commented on Dockerfile
> +  && set -x \
Duplicated

2017-10-25 17:02 UTC, rporres commented on Dockerfile
> +  && set -x \
thx, that comes from the refactor.

2017-10-25 17:14 UTC, rporres commented
Apologies for adding more lines after the review, but I was able to save almost 30mb doing it.

2017-10-26 08:07 UTC, smeruelo approved these changes

2017-10-26 08:26 UTC, merged